In [1]:
pip install statistics

  Created wheel for statistics: filename=statistics-1.0.3.5-py3-none-any.whl size=7452 sha256=e415e89813f24eae35130958de953ecea2069799b095b06fb87840469685e7dd
  Stored in directory: c:\users\jktadi\appdata\local\pip\cache\wheels\26\3c\70\9467407f3aa90862061eadcd286627b23a8bab6789b667776f
Successfully built statistics
Note: you may need to restart the kernel to use updated packages.


In [2]:
!pip install statistics

In [4]:
 import statistics as start

In [9]:
 import statistics as stat

In [10]:
 import statistics as stat

In [11]:
stat.mean([1,2,3,4,5])

3

In [12]:
stat.median([1,2,3,4,5,6,7,10])

4.5

In [13]:
stat.median{[1,2,3,7,8,10]}

SyntaxError: invalid syntax (Temp/ipykernel_6700/2665641352.py, line 1)

In [15]:
stat.median([1,2,3,7,8,9])

5.0

In [16]:
stat.median_low([1,2,3,4,5,6,7,10])

4

In [17]:
stat.median_high([1,2,3,4,5,6,7,10])

5

In [18]:
stat.median([1,2,3,7,6,6,6,8,9])

6

In [19]:
stat.mode([1,2,3,4,5,6,7,10,2])

2

In [20]:
stat.median([1,2,3,4,5,6,7,8])

4.5

In [21]:
stat.median([1,2,3,4,5,6,7,10])

4.5

In [22]:
stat.median([1,2,3,4,5,6,7,15])

4.5

In [24]:
stat.median([1,6,7,8,9,10,11,12])

8.5

In [25]:
stat.median([3,6,7,8,9,10,11,12])

8.5

In [26]:
stat.median([3,6,7,8,9,10,100,120])

8.5

In [27]:
stat.stdev([89,54,98,76,87,87,82,90,78,80])

11.826993606905255

In [28]:
stat.mean([89,54,98,76,87,87,82,90,78,80])

82.1

In [29]:
import numpy as np

In [34]:
a= np.arange(1,9)
print( a)

[1 2 3 4 5 6 7 8]


In [35]:
print(a[1])

2


In [36]:
a=a.reshape([2,4])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [37]:
a=a.reshape((2,4)) # ini keterangan matrix 2, 4
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [38]:
print (np.mean(a))

4.5


In [47]:
print(np.random.shuffle(a))

None


In [40]:
np.random.shuffle(a)

In [44]:
np.random.shuffle(a)
print (a)

[[1 2 3 4]
 [5 6 7 8]]


In [45]:
print (np.min(a))

1


In [53]:
print(np.max(a))

8


In [57]:
c=np.array([10,15,100,200,300])
print(np.median(c))

100.0


In [58]:
git version

SyntaxError: invalid syntax (Temp/ipykernel_6700/1149855917.py, line 1)